language: node_js
node_js:
  - "node"
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
after_success:
  - yarn run coverage
notifications:
  email:
    recipients:
      - notify@barbatti.de
  on_success: always
